### ISSUE TITLE
New step in tests

### ISSUE THREAD

**Issue by AndrewOvvv** [Minecraft-Unified-Hub-Team/ServerControl#23]
I think that we need something like StepTimeout or StepSleep

**Comment by AndrewOvvv** [comment]
@noname0443 can you write code for that steps pls

**Comment by noname0443** [comment]
Could you share a bit more about why adding a separate `StepTimeout` or `StepSleep` would be beneficial? From what I see, it looks like we can already control the timeout here: [options.feature](https://github.com/Minecraft-Unified-Hub-Team/ServerControl/blob/dev/tests/features/options.feature).
